### ISSUE TITLE
add autoSizing to text inside FortyAhadith 

### ISSUE THREAD

**Issue by MahmoudMabrok** [hamza94max/Wazkar#16]
- make text auto sized  with card

**Comment by hamza94max** [comment]
@MahmoudMabrok Do u mean this attribute  /  app:autoSizeTextType="uniform"

**Comment by MahmoudMabrok** [comment]
yes

**Comment by hamza94max** [comment]
you can use all these like that :
//TextView
    app:autoSizeTextType="uniform"
    app:autoSizeMinTextSize="16sp"
    app:autoSizeMaxTextSize="100sp"
    app:autoSizeStepGranularity="1sp" />

https://medium.com/over-engineering/making-the-most-of-textview-auto-sizing-on-android-a39f71b6f3af
