### ISSUE TITLE
Min_Sdk

### ISSUE THREAD

**Issue by hamza94max** [hamza94max/Wazkar#17]
![ass](https://user-images.githubusercontent.com/54688005/93001963-6aabc280-f533-11ea-9e5c-60ec7c330e3e.PNG)

this advice do not run my app 

min sdk =14 , I can not decrease it 

@MahmoudMabrok

**Comment by MahmoudMabrok** [comment]
we did not need to decrease as device API is more that 14 also 
google recommend min sdk to be 21

**Comment by MahmoudMabrok** [comment]
explain issue with more clearfication and more context i.e 
- it crash at startup? 
- can not be installed? 
or what?

**Comment by hamza94max** [comment]
I know that <br/>
install successfully but the app is **not opening** as the device version 6

**Comment by hamza94max** [comment]
guess what ? <br/>
the problem because some of the images in drawable v24 ,it should be both v24 and manual <br/>
the problem is solved and I will update @MahmoudMabrok

**Comment by MahmoudMabrok** [comment]
remove v24 folder if u dont need it

**Comment by hamza94max** [comment]
ok
