### ISSUE TITLE
Apply Review process

### ISSUE THREAD

**Issue by MahmoudMabrok** [hamza94max/Wazkar#18]
will make `dev` branch will develop and solve issue on it
and when finish we do a PR to master and request code review from our peer

**Comment by hamza94max** [comment]
No one review yet !

**Comment by MahmoudMabrok** [comment]
u should first make changes and create PR then assign me

**Comment by hamza94max** [comment]
Make a branch **dev** now ?

**Comment by MahmoudMabrok** [comment]
do it

**Comment by hamza94max** [comment]
Done @MahmoudMabrok
